version: '3.8'

services:
    backend:
        build: ./backend
        image: recipe-app-api
        restart: unless-stopped
        volumes:
            - ./backend/src:/app/src
        env_file:
            - ./backend/local.docker.env
        # depends_on:
        #     - db
        ports:
            - '5000:5000'
    frontend:
        build: ./frontend
        image: recipe-app-frontend
        volumes:
            - ./frontend/src:/app/src
        environment:
            - VITE_API_BASE_URL=http://localhost:5000
        ports:
            - '5173:5173'

    db:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=development
            - POSTGRES_USER=postgres
            - POSTGRES_DB=dev_db
volumes:
    postgres_data:
